### ISSUE TITLE
Segmentation fault error; distributed learning

### ISSUE THREAD

**Issue by 4ound** [aksnzhy/xlearn#284]
1. Number of features * k > uint32
You'll get error "Segmentation fault" while training
I read your code and found two lines, where 
`
typedef uint32 index_t;
`
I've changed it to
`
typedef uint64 index_t;
`
After that everything worked ok. But I'm not sure, is it correct? Could it broke some computations?

2.  Distributed learning
Judging by your docs, model should support distributed training.
Could you tell the idea of implementation?
Will you implement it soon?

**Comment by aksnzhy** [comment]
@4ound Hi, thanks for the attention of xLearn. 

1. We use uint32 by default because of the performance concern. You can change it to uint64 for your case.

2. For distributed training, we have an internal version of that but I think it's not ready to release. I will release it in the future, but we don't have a concrete deadline. 

Thanks!

**Comment by 4ound** [comment]
Thanks
